"""NetBox-specific semantic mock value generators."""

from __future__ import annotations

import hashlib
from typing import Any


def _seed_int(seed: str, *, modulus: int, offset: int = 0) -> int:
    """Deterministic integer from a seed string using SHA-1."""
    digest = hashlib.sha1(seed.encode("utf-8")).hexdigest()
    return (int(digest[:8], 16) % modulus) + offset


def semantic_netbox_value(
    *,
    field_name: str | None,
    seed: str,
    schema: dict[str, Any] | None = None,
) -> Any:
    """Return a semantically meaningful mock value for common NetBox field names.

    Returns None when no specific semantic applies, signalling the caller to
    fall back to generic schema-typed generation.
    """
    hint = (field_name or "").strip().lower()
    if not hint:
        return None

    idx = _seed_int(seed, modulus=99, offset=1)
    host_idx = _seed_int(seed, modulus=8, offset=1)
    ip_b = _seed_int(seed, modulus=200, offset=10)
    ip_c = _seed_int(seed + "c", modulus=200, offset=10)

    # --- Status-like fields ---
    if hint == "status":
        return "active"
    if hint == "color":
        colors = [
            "aa1409",
            "f44336",
            "e91e63",
            "ff5722",
            "ff9800",
            "ffc107",
            "ffeb3b",
            "4caf50",
            "2196f3",
            "9c27b0",
        ]
        return colors[_seed_int(seed, modulus=len(colors))]

    # --- Naming fields ---
    if hint in ("name", "label"):
        return f"mock-{idx:02d}"
    if hint == "slug":
        return f"mock-{idx:02d}"
    if hint == "description":
        return "Mock description generated by netbox-sdk mock server"
    if hint == "comments":
        return ""

    # --- Network addressing ---
    if hint in ("address",):
        return f"10.{host_idx}.{ip_b}.{ip_c}/32"
    if hint in ("prefix",):
        return f"10.{host_idx}.{ip_b}.0/24"
    if hint in ("ip_address", "ip"):
        return f"10.{host_idx}.{ip_b}.{ip_c}"
    if hint in ("gateway",):
        return f"10.{host_idx}.{ip_b}.1"
    if hint in ("mac_address", "mac"):
        b1 = 0x52
        b2 = _seed_int(seed + "m2", modulus=256)
        b3 = _seed_int(seed + "m3", modulus=256)
        b4 = _seed_int(seed + "m4", modulus=256)
        b5 = _seed_int(seed + "m5", modulus=256)
        b6 = _seed_int(seed + "m6", modulus=256)
        return f"{b1:02X}:{b2:02X}:{b3:02X}:{b4:02X}:{b5:02X}:{b6:02X}"
    if hint in ("cidr", "subnet"):
        return f"10.{host_idx}.{ip_b}.0/24"
    if hint in ("vid", "vlan_id", "vlan"):
        return _seed_int(seed, modulus=4094, offset=1)
    if hint == "asn":
        return _seed_int(seed, modulus=1022, offset=64512)
    if hint == "rd":
        return f"65000:{idx}"
    if hint in ("interface", "iface"):
        choices = [
            "GigabitEthernet0/0/0",
            "GigabitEthernet0/0/1",
            "TenGigabitEthernet0/0/0",
            "Management0",
        ]
        return choices[_seed_int(seed, modulus=len(choices))]
    if hint in ("port", "tcp_port", "udp_port"):
        return _seed_int(seed, modulus=60000, offset=1024)

    # --- Site/Rack/Device identifiers ---
    if hint == "site":
        return None  # nested object — caller handles
    if hint in ("rack_unit", "position", "u_height"):
        return _seed_int(seed, modulus=42, offset=1)
    if hint == "face":
        return "front"
    if hint in ("width",):
        return 19
    if hint in ("u_height",):
        return _seed_int(seed, modulus=10, offset=1)

    # --- Timestamps ---
    if hint in ("created", "last_updated"):
        return "2025-01-15T10:00:00Z"
    if hint in ("date", "date_installed"):
        return "2025-01-15"

    # --- URL fields ---
    if hint == "url" or hint.endswith("_url"):
        return f"http://mock.example.com/api/mock/{idx}/"

    # --- Display string ---
    if hint == "display":
        return f"Mock Object {idx:02d}"

    # --- ID fields ---
    if hint == "id":
        return idx

    return None


__all__ = ["semantic_netbox_value"]
